### ISSUE TITLE
I don't know why you think this is unusable

### ISSUE THREAD

**Issue by csells** [pmtothemoon/unusable_player#1]
I personally love the hand drawn style. I want a whole set of widgets in this style!

**Comment by pierremrtn** [comment]
Thank you :)
But actually the credits go to Sulton Handaya, the author of my reference mockups. All I did is just copying.
Actually, the name "unusable player" was a joke because of it's focus on UI looks at the expense of the UX.
I'm not planning to put myself into doing a package with widgets in this style, but feel free to use unusable_player as source of inspiration if you want to do so 🚀💙
